
package com.oracle.xmlns.pcbpel.adapter.db.pocvendorinfo.vendorinfo.bam_dev;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.xmlns.pcbpel.adapter.db.top.bam_dev.BAMDEVSelectId;
import com.oracle.xmlns.pcbpel.adapter.db.top.bam_dev.ObjectFactory;
import com.oracle.xmlns.pcbpel.adapter.db.top.bam_dev.VendorinfoCollection;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BAM_DEV_ptt", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/POCVendorInfo/VendorInfo/BAM_DEV")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BAMDEVPtt {


    /**
     * 
     * @param vendorinfoCollection
     */
    @WebMethod(action = "merge")
    @Oneway
    public void merge(
        @WebParam(name = "VendorinfoCollection", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/top/BAM_DEV", partName = "VendorinfoCollection")
        VendorinfoCollection vendorinfoCollection);

    /**
     * 
     * @param bamDEVSelectInputParameters
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.top.bam_dev.VendorinfoCollection
     */
    @WebMethod(operationName = "BAM_DEVSelect", action = "BAM_DEVSelect")
    @WebResult(name = "VendorinfoCollection", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/top/BAM_DEV", partName = "VendorinfoCollection")
    public VendorinfoCollection bamDEVSelect(
        @WebParam(name = "BAM_DEVSelect_id", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/top/BAM_DEV", partName = "BAM_DEVSelect_inputParameters")
        BAMDEVSelectId bamDEVSelectInputParameters);

}
